using System;
using CommNet;
using UnityEngine;

namespace RSCKerbalismED.Source.Services;

/// <summary>
/// Provides RSCKE's runtime Terminal GUI behavior.
/// </summary>
internal static class RSCKETerminalService
{
    /// <summary>
    /// Safely gets the number of stored science data entries.
    /// </summary>
    /// <param name="container">The science container.</param>
    /// <returns>The number of stored entries, or zero if the container is null.</returns>
    internal static int SafeGetStoredDataCount(ModuleScienceContainer container)
    {
        if (container == null)
            return 0;

        return container.GetStoredDataCount();
    }

    /// <summary>
    /// Safely gets the science container capacity.
    /// </summary>
    /// <param name="container">The science container.</param>
    /// <returns>The container capacity, or zero if the container is null.</returns>
    internal static int SafeGetCapacity(ModuleScienceContainer container)
    {
        if (container == null)
            return 0;

        return container.capacity;
    }

    /// <summary>
    /// Suppresses the RSC Science Loss due to Reuse GUI label.
    /// </summary>
    /// <param name="text">The label text generated by RSC.</param>
    /// <param name="style">The label style generated by RSC.</param>
    public static void HideReuseLossLabel(string text, GUIStyle style, GUILayoutOption[] options)
    {
    }

    /// <summary>
    /// Closes the RSC terminal when there's no longer full
    /// control of the vessel via CommNet.
    /// </summary>
    /// <param name="roverInstance">The RSC RoverScience instance whose terminal should be checked.</param>
    public static void CloseTerminalWhenFullControlLost(RoverScience.RoverScience roverInstance)
    {
        ModuleCommand command = roverInstance.command;
        if (command != null)
        {
            VesselControlState controlState = command.VesselControlState;
            if (controlState != VesselControlState.Full &&
                controlState != VesselControlState.ProbeFull)
            {
                if (roverInstance.IsPrimary
                    && roverInstance.roverScienceGUI?.consoleGUI != null
                    && roverInstance.roverScienceGUI.consoleGUI.isOpen)
                {
                    // TODO: method to "Shutdown" - Resetscience spot, hide terminal, etc..
                    roverInstance.roverScienceGUI.consoleGUI.Hide();
                    Debug.Log("[RSCKerbalismED] INFO: RSC terminal closed because rover control was lost. " +
                        "Control state: " + controlState);
                }
            }
        }
    }
}