using System;
using System.Collections.Generic;
using CommNet;
using UnityEngine;

namespace RSCKerbalismED.Source.Services;

/// <summary>
/// Provides RSCKE's runtime Terminal GUI behavior.
/// </summary>
internal static class RSCKETerminalService
{
    private static readonly Dictionary<RoverScience.RoverScience, bool> terminalStates = new();

    /// <summary>
    /// Safely gets the number of stored science data entries.
    /// </summary>
    /// <param name="container">The science container.</param>
    /// <returns>The number of stored entries, or zero if the container is null.</returns>
    internal static int SafeGetStoredDataCount(ModuleScienceContainer container)
    {
        if (container == null)
            return 0;

        return container.GetStoredDataCount();
    }

    /// <summary>
    /// Safely gets the science container capacity.
    /// </summary>
    /// <param name="container">The science container.</param>
    /// <returns>The container capacity, or zero if the container is null.</returns>
    internal static int SafeGetCapacity(ModuleScienceContainer container)
    {
        if (container == null)
            return 0;

        return container.capacity;
    }

    /// <summary>
    /// Suppresses the RSC Science Loss due to Reuse GUI label.
    /// </summary>
    /// <param name="text">The label text generated by RSC.</param>
    /// <param name="style">The label style generated by RSC.</param>
    public static void HideReuseLossLabel(string text, GUIStyle style, GUILayoutOption[] options)
    {
    }

    /// <summary>
    /// Closes the RSC terminal when there's no longer full
    /// control of the vessel via CommNet.
    /// </summary>
    /// <param name="roverInstance">The RSC RoverScience instance whose terminal should be checked.</param>
    public static void CloseTerminalWhenFullControlLost(RoverScience.RoverScience roverInstance)
    {
        ModuleCommand command = roverInstance.command;
        if (command != null)
        {
            VesselControlState controlState = command.VesselControlState;
            if (controlState != VesselControlState.Full &&
                controlState != VesselControlState.ProbeFull)
            {
                if (roverInstance.IsPrimary
                    && roverInstance.roverScienceGUI?.consoleGUI != null
                    && roverInstance.roverScienceGUI.consoleGUI.isOpen)
                {
                    // TODO: method to "Shutdown" - Resetscience spot, hide terminal, etc.. 
                    roverInstance.roverScienceGUI.consoleGUI.Hide();
                    RSCKELogger.Info("RSC terminal closed because rover control was lost. " +
                        "Control state: " + controlState);
                }
            }
        }
    }

    /// <summary>
    /// Synchronizes the RSC Rover Terminal state with the Kerbalism experiment state.
    /// </summary>
    /// <param name="experiment">The Kerbalism Experiment instance.</param>
    internal static void SyncRSCConsoleToKerbalismState(KERBALISM.Experiment experiment)
    {
        if (experiment == null)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: Kerbalism Experiment is null.");
            return;
        }

        RoverScience.RoverScience roverScience = null;

        foreach (PartModule module in experiment.part.Modules)
        {
            RoverScience.RoverScience candidate = module as RoverScience.RoverScience;
            if (candidate != null)
            {
                roverScience = candidate;
                break;
            }
        }

        if (roverScience == null)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: RoverScience module was not found. " +
                "Experiment instance ID=" + experiment.GetInstanceID() + ".");
            return;
        }

        if (!roverScience.IsPrimary)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: RoverScience instance is not primary. " +
                "RSC instance ID=" + roverScience.GetInstanceID() + ".");
            return;
        }

        if (roverScience.roverScienceGUI?.consoleGUI == null)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: consoleGUI is null. " +
                "RSC instance ID=" + roverScience.GetInstanceID() + ".");
            return;
        }

        bool terminalOpen = roverScience.roverScienceGUI.consoleGUI.isOpen;
        bool experimentRunning = experiment.Running;

        RSCKELogger.Info("Kerbalism Experiment state changed. " +
            "Experiment instance ID=" + experiment.GetInstanceID() +
            ", State=" + experiment.State +
            ", Running=" + experimentRunning +
            ", TerminalOpen=" + terminalOpen + ".");

        if (experimentRunning && !terminalOpen)
        {
            RSCKELogger.Info("Kerbalism Experiment is Running and RSC Terminal is closed. Opening RSC Terminal.");

            roverScience.roverScienceGUI.consoleGUI.Toggle();

            RSCKELogger.Info("RSC Terminal opened from Kerbalism Experiment state. " +
                "TerminalOpen=" + roverScience.roverScienceGUI.consoleGUI.isOpen + ".");
        }
        else if (!experimentRunning && terminalOpen)
        {
            RSCKELogger.Info("Kerbalism Experiment is Stopped and RSC Terminal is open. Closing RSC Terminal.");

            roverScience.roverScienceGUI.consoleGUI.Hide();

            RSCKELogger.Info("RSC Terminal closed from Kerbalism Experiment state. " +
                "TerminalOpen=" + roverScience.roverScienceGUI.consoleGUI.isOpen + ".");
        }
    }

    /// <summary>
    /// Synchronizes the Kerbalism experiment state with changes to the RSC Rover Terminal state.
    /// </summary>
    /// <param name="roverScience">The RSC RoverScience instance.</param>
    public static void SyncKerbalismExperimentState(RoverScience.RoverScience roverScience)
    {
        if (roverScience == null)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: roverScience is null.");
            return;
        }

        if (!roverScience.IsPrimary)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: RoverScience instance is not primary. " +
                "RSC instance ID=" + roverScience.GetInstanceID() + ".");
            return;
        }

        if (roverScience.roverScienceGUI?.consoleGUI == null)
        {
            RSCKELogger.Info("RSC Terminal synchronization skipped: consoleGUI is null. " +
                "RSC instance ID=" + roverScience.GetInstanceID() + ".");
            return;
        }

        bool terminalOpen = roverScience.roverScienceGUI.consoleGUI.isOpen;

        RSCKELogger.Info("RSC Terminal synchronization check. " +
            "RSC instance ID=" + roverScience.GetInstanceID() +
            ", TerminalOpen=" + terminalOpen +
            ", IsPrimary=" + roverScience.IsPrimary + ".");

        if (!terminalStates.TryGetValue(roverScience, out bool previousTerminalOpen))
        {
            terminalStates[roverScience] = terminalOpen;

            RSCKELogger.Info("RSC Terminal synchronization initialized. " +
                "RSC instance ID=" + roverScience.GetInstanceID() +
                ", TerminalOpen=" + terminalOpen + ".");

            return;
        }

        if (previousTerminalOpen == terminalOpen)
        {
            RSCKELogger.Info("RSC Terminal synchronization: no terminal state change. " +
                "RSC instance ID=" + roverScience.GetInstanceID() +
                ", TerminalOpen=" + terminalOpen + ".");
            return;
        }

        terminalStates[roverScience] = terminalOpen;

        RSCKELogger.Info("RSC Terminal state changed. " +
            "RSC instance ID=" + roverScience.GetInstanceID() +
            ", PreviousOpen=" + previousTerminalOpen +
            ", CurrentOpen=" + terminalOpen + ".");

        KERBALISM.Experiment experiment = null;

        foreach (PartModule module in roverScience.part.Modules)
        {
            KERBALISM.Experiment candidate = module as KERBALISM.Experiment;
            if (candidate != null && candidate.experiment_id == RSCKEConstants.ROVER_EXPERIMENT_ID)
            {
                experiment = candidate;
                break;
            }
        }

        if (experiment == null)
        {
            RSCKELogger.Error("RSC Terminal synchronization failed: Kerbalism Experiment ID '" +
                RSCKEConstants.ROVER_EXPERIMENT_ID + "' was not found on the rover part.");
            return;
        }

        RSCKELogger.Info("RSC Terminal synchronization selected Kerbalism Experiment. " +
            "Experiment instance ID=" + experiment.GetInstanceID() +
            ", experiment_id=" + experiment.experiment_id +
            ", State=" + experiment.State +
            ", Running=" + experiment.Running + ".");

        if (terminalOpen && experiment.State == KERBALISM.Experiment.RunningState.Stopped)
        {
            RSCKELogger.Info("RSC Terminal opened and Kerbalism Experiment is Stopped. " +
                "Calling Experiment.Toggle().");

            experiment.Toggle();

            RSCKELogger.Info("RSC Terminal open Toggle() returned. " +
                "Experiment instance ID=" + experiment.GetInstanceID() +
                ", State=" + experiment.State +
                ", Running=" + experiment.Running + ".");
        }
        else if (!terminalOpen && experiment.State != KERBALISM.Experiment.RunningState.Stopped)
        {
            RSCKELogger.Info("RSC Terminal closed and Kerbalism Experiment is not Stopped. " +
                "Calling Experiment.Toggle().");

            experiment.Toggle();

            RSCKELogger.Info("RSC Terminal closed Toggle() returned. " +
                "Experiment instance ID=" + experiment.GetInstanceID() +
                ", State=" + experiment.State +
                ", Running=" + experiment.Running + ".");
        }
        else
        {
            RSCKELogger.Info("RSC Terminal synchronization made no Kerbalism state change. " +
                "TerminalOpen=" + terminalOpen +
                ", Experiment State=" + experiment.State +
                ", Running=" + experiment.Running + ".");
        }
    }
}