<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>RSCKerbalismED</AssemblyName>

    <RootNamespace>RSCKerbalismED</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>

    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <OutputPath>$(MSBuildThisFileDirectory)Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!-- KSP -->
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>..\..\KSP_x64_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\KSP_x64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- Harmony 2 -->
    <Reference Include="0Harmony">
      <HintPath>..\000_Harmony\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- Kerbalism -->
    <Reference Include="Kerbalism">
      <HintPath>..\Kerbalism\Kerbalism.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- RoverScience Continued -->
    <Reference Include="RoverScienceCont">
      <HintPath>..\RoverScience\Plugins\RoverScienceCont.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>